# Name of workflow
name: Test

# Trigger the workflow on push and pull request events to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  # Define a job named "ci"
  ci:
    # Specify the operating system to run the job on
    runs-on: ubuntu-latest

    # Define the steps to be executed
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run component tests
      - name: Run component tests
        run: npm run test:component

      # Define a step named "Deploy"
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        # Set an environment variable with the deployment URL from secrets
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        # Run the deployment command
        run: |
          curl "$DEPLOY_URL"